### ISSUE TITLE
Changes on Token Price should automatically impact Vol and Liq variables

### ISSUE THREAD

**Issue by gurelcan** [cangurel90/uniswap_lp_roi#3]
For accurate pool ROI and fee calculations the Volume and Liquidity inputs must automatically change according to Token1 and Token2 price changes. Formulas are correct but they take on initial VOL and LIQ figures instead of LIQ_after_appreciation and VOL_after_appreciation therefore result in wrong number when token prices are altered

**Comment by cangurel90** [comment]
For accurate pool ROI and fee calculations the Volume and Liquidity inputs must automatically change according to Token1 and Token2 price changes. Formulas are correct but they take on initial VOL and LIQ figures instead of LIQ_after_appreciation  and VOL_after_appreciation therefore result in wrong number when token prices are altered

**Comment by gurelcan** [comment]
right now all the calculations are correct and thank you that. The calculation take into account liq_after_appreciation and vol_after_appreacation as it should be. Also when liq and vol figures are further change it reflects on calculations correctly.

the only thing left here is the display of liq and volumes sliders. 

When price of tokens are changed, instead of inital figures the sliders must adjust to show liq_after_appreciation and vol_after_appreacation figures. Let me know if anything is unclear here
